/* eslint-disable no-unused-labels */
import { defineStore } from 'pinia'

export const useExcercisesStore = defineStore('excercises', {
  state: () => {
      return { excercises: [
        {
          id:'exc01',
          title: 'Упражнение 1',
          subtitle: 'Дегенерация, Протеинови дегенерации, Хиалиноза',
          images: [
            { filename:'exc-01/Degeneratio hyalinosa musculorum agne_182_a.JPG', name: 'Degeneratio hyalinosa musculorum', sample: 'agne_182_a', class:'Degeneratio hyalinosa musculorum agne',description:''},
            { filename:'exc-01/Degeneratio hyalinosa musculorum_agne_182_a.JPG', name: 'Degeneratio hyalinosa musculorum', sample: 'agne_182_a', class:'Degeneratio hyalinosa musculorum agne',description:''},
            { filename:'exc-01/Degeneratio hyalinosa renis_182_b_cow.JPG', name: 'Degeneratio hyalinosa renis', sample: '182_b_cow', class:'Degeneratio hyalinosa renis cow',description:''},
            { filename:'exc-01/Degeneratio hyalinosa renis_182_b_cow (2).JPG', name: 'Degeneratio hyalinosa renis', sample: '182_b_cow', class:'Degeneratio hyalinosa renis cow',description:''},
            { filename:'exc-01/Degeneratio hyalinosa renis_182_b_cow (3).JPG', name: 'Degeneratio hyalinosa renis', sample: '182_b_cow', class:'Degeneratio hyalinosa renis cow',description:''},
            { filename:'exc-01/Degeneratio hyalinosa renis_182_b_cow (4).JPG', name: 'Degeneratio hyalinosa renis', sample: '182_b_cow', class:'Degeneratio hyalinosa renis cow',description:''},
            { filename:'exc-01/Degeneratio parenchymatosa hepatis 234.jpg', name: 'Degeneratio parenchymatosa hepatis', sample: '234', class:'Degeneratio parenchymatosa hepatis',description:''},
            { filename:'exc-01/Degeneratio parenchymatosa hepatis 234 (2).JPG', name: 'Degeneratio parenchymatosa hepatis', sample: '234', class:'Degeneratio parenchymatosa hepatis',description:''},
            { filename:'exc-01/Degeneratio parenchymatosa hepatis 234 (3).JPG', name: 'Degeneratio parenchymatosa hepatis', sample: '234', class:'Degeneratio parenchymatosa hepatis',description:''},
            { filename:'exc-01/Degeneratio parenchymatosa renis 245 .JPG', name: 'Degeneratio parenchymatosa renis', sample: '245', class:'Degeneratio parenchymatosa renis',description:''},
            { filename:'exc-01/Degeneratio parenchymatosa renis 245  (2).JPG', name: 'Degeneratio parenchymatosa renis', sample: '245', class:'Degeneratio parenchymatosa renis',description:''},
          ]
        },
        {
          id:'exc02',
          title: 'Упражнение 2',
          subtitle: 'Амилоидна, Кератиноидна и Колоидна дегенерации',
          images: [
            { filename:'exc-02/Amyloidosis lienis B-219a-1.JPG', name: 'Amyloidosis lienis', sample: 'B-219a-1', class: 'Amyloidosis lienis', description:''},
            { filename:'exc-02/Amyloidosis lienis B-219a-2.JPG', name: 'Amyloidosis lienis', sample: 'B-219a-2', class: 'Amyloidosis lienis', description:''},
            { filename:'exc-02/Amyloidosis lienis B-219a-3.JPG', name: 'Amyloidosis lienis', sample: 'B-219a-3', class: 'Amyloidosis lienis', description:''},
            { filename:'exc-02/Amyloidosis hepatis 27_a.JPG', name: 'Amyloidosis hepatis', sample: 'A-27a-1', class: 'Amyloidosis hepatis', description:''},
            { filename:'exc-02/Amyloidosis hepatis A-27a-2.JPG', name: 'Amyloidosis hepatis', sample: 'A-27a-2', class: 'Amyloidosis hepatis', description:''},
            { filename:'exc-02/Amyloidosis hepatis A-27a-3.JPG', name: 'Amyloidosis hepatis', sample: 'A-27a-3', class: 'Amyloidosis hepatis', description:''},
            { filename:'exc-02/Cancroid D-127a-1.JPG', name: 'Cancroid', sample: 'D-127a-1', class: 'Cancroid', description:''},
            { filename:'exc-02/Cancroid D-127a-2.JPG', name: 'Cancroid', sample: 'D-127a-2', class: 'Cancroid', description:''},
            { filename:'exc-02/Hyperplasia et prosoplasia glandulae mucosae E-258-1.JPG', name: 'Hyperplasia et prosoplasia glandulae mucosae', sample: 'E-258-1', class: 'Hyperplasia et prosoplasia glandulae mucosae', description:''},
            { filename:'exc-02/Hyperplasia et prosoplasia glandulae mucosae E-258-2.JPG', name: 'Hyperplasia et prosoplasia glandulae mucosae', sample: 'E-258-2', class: 'Hyperplasia et prosoplasia glandulae mucosae', description:''},
            { filename:'exc-02/Hyperplasia et prosoplasia glandulae mucosae E-258-3.JPG', name: 'Hyperplasia et prosoplasia glandulae mucosae', sample: 'E-258-3', class: 'Hyperplasia et prosoplasia glandulae mucosae', description:''},
            { filename:'exc-02/Ichtiosis congenita C 205 1.JPG', name: 'Ichtiosis congenita', sample: 'C 205 1', class: 'Ichtiosis congenita', description:''},
            { filename:'exc-02/Ichtiosis congenita C 205 2.JPG', name: 'Ichtiosis congenita', sample: 'C 205 2', class: 'Ichtiosis congenita', description:''},
            { filename:'exc-02/Struma colloidesF-96-1.JPG', name: 'Struma colloides', sample: 'F-96-1', class: 'Struma colloides', description:''},
            { filename:'exc-02/Struma colloidesF-96-2.JPG', name: 'Struma colloides', sample: 'F-96-2', class: 'Struma colloides', description:''},
          ]
        },
        {
        id:'exc03',
          title: 'Упражнение 3',
          subtitle: 'Нуклеопротеидни дегенерации, Патологични пигментации',
          images: [
            { filename:'exc-03/Anthracosis noduli lumphatici G-137b-1.JPG', name: 'Anthracosis noduli lumphatici', sample: 'G-137b-1', class: 'Anthracosis noduli lumphatici', description:''},
            { filename:'exc-03/Anthracosis noduli lymphaticiG-137b-2.JPG', name: 'Anthracosis noduli lymphatici', sample: 'G-137b-2', class: 'Anthracosis noduli lumphatici', description:''},
            { filename:'exc-03/Anthracosis noduli lymphatici G-137b-3.JPG', name: 'Anthracosis noduli lymphatici', sample: 'G-137b-3', class: 'Anthracosis noduli lumphatici', description:''},
            { filename:'exc-03/Anthracosis pulmonum F-137a-1.JPG', name: 'Anthracosis pulmonum', sample: 'F-137a-1', class: 'Anthracosis pulmonum', description:''},
            { filename:'exc-03/Anthracosis pulmonum F-137a-2.JPG', name: 'Anthracosis pulmonum', sample: 'F-137a-2', class: 'Anthracosis pulmonum', description:''},
            { filename:'exc-03/Icterus E-28a-1.JPG', name: 'Icterus', sample: 'E-28a-1', class: 'Icterus', description:''},
            { filename:'exc-03/Icterus E-28a-2.JPG', name: 'Icterus', sample: 'E-28a-2', class: 'Icterus', description:''},
            { filename:'exc-03/Icterus E-28a-3.JPG', name: 'Icterus', sample: 'E-28a-3', class: 'Icterus', description:''},
            { filename:'exc-03/Hemosiderosis hepatis D-264-1.JPG', name: 'Hemosiderosis hepatis', sample: 'D-264-1', class: 'Hemosiderosis hepatis', description:''},
            { filename:'exc-03/Haemosiderosis hepatis D-264-2.JPG', name: 'Hemosiderosis hepatis', sample: 'D-264-2', class: 'Hemosiderosis hepatis', description:''},
            { filename:'exc-03/Diathesis urica A-109-1.JPG', name: 'Diathesis urica', sample: 'A-109-1', class: 'Diathesis urica', description:''},
            { filename:'exc-03/Diathesis uricaA-109-2.JPG', name: 'Diathesis urica', sample: 'A-109-2', class: 'Diathesis urica', description:''},
            { filename:'exc-03/Diathesis urica A-109-3.JPG', name: 'Diathesis urica', sample: 'A-109-3', class: 'Diathesis urica', description:''},
            { filename:'exc-03/Melanosis maculosa C-53b-1.JPG', name: 'Melanosis maculosa', sample: 'C-53b-1', class: 'Melanosis maculosa', description:''},
            { filename:'exc-03/Melanosis maculosa C-53b-2.JPG', name: 'Melanosis maculosa', sample: 'C-53b-2', class: 'Melanosis maculosa', description:''},
            { filename:'exc-03/Xantinosis renis B-79-1.JPG', name: 'Xantinosis renis', sample: 'B-79-1', class: 'Xantinosis renis', description:''},
            { filename:'exc-03/Xantinosis renis B-79-2.JPG', name: 'Xantinosis renis', sample: 'B-79-2', class: 'Xantinosis renis', description:''},
            { filename:'exc-03/Xantinosis renis B-79-3.JPG', name: 'Xantinosis renis', sample: 'B-79-3', class: 'Xantinosis renis', description:''},
          ]
        },
        {
          id:'exc04',
          title: 'Упражнение 4',
          subtitle: 'Дегенерации асоциирани с метаболизъм на мазнини и минерали',
          images: [
            { filename:'exc-04/atheromatosis aortae C-221_1.jpg', name: 'Atheromatosis aortae C-221_1', sample: '', class: '', description:''},
            { filename:'exc-04/Atheromatosis aortae C-221_2.jpg', name: 'Atheromatosis aortae C-221_2', sample: '', class: '', description:''},
            { filename:'exc-04/Atheromatosis aortaeC-221_3.jpg', name: 'Atheromatosis aortae C-221_3', sample: '', class: '', description:''},
            { filename:'exc-04/Atheromatosis aortae C-221_4.jpg', name: 'Atheromatosis aortae C-221_4', sample: '', class: '', description:''},
            { filename:'exc-04/Degeneratio lipomatosa hepatis B-226_1.jpg', name: 'Degeneratio lipomatosa hepatis B-226_1', sample: '', class: '', description:''},
            { filename:'exc-04/Degeneratio lipomatosa hepatisB-226_2.jpg', name: 'Degeneratio lipomatosa hepatis B-226_2', sample: '', class: '', description:''},
            { filename:'exc-04/Infiltratio lipomatosa hepatis A-227_1.jpg', name: 'Infiltratio lipomatosa hepatis A-227_1', sample: '', class: '', description:''},
            { filename:'exc-04/Infiltratio lipomatosa hepatis A-227_2.jpg', name: 'Infiltratio lipomatosa hepatis A-227_2', sample: '', class: '', description:''},
            { filename:'exc-04/histohimia cordis 3.jpg', name: 'Histohimia cordis 3', sample: '', class: '', description:''},
            { filename:'exc-04/Osteodystrophia fibrosa E-37a_1.jpg', name: 'Osteodystrophia fibrosa E-37a_1', sample: '', class: '', description:''},
            { filename:'exc-04/Osteodystrophia fibrosa E-37a_2.jpg', name: 'Osteodystrophia fibrosa E-37a_2', sample: '', class: '', description:''},
            { filename:'exc-04/Osteodystrophia fibrosa E-37a_3.JPG', name: 'Osteodystrophia fibrosa E-37a_3', sample: '', class: '', description:''},
            { filename:'exc-04/Necroses myocardii. Calcificatio. Hypovitaminosis E D-63a-1.jpg', name: 'Necroses myocardii. Calcificatio. Hypovitaminosis', sample: 'E D-63a-1', class: '', description:''},
            { filename:'exc-04/NECROSES MYOCARDII D-63a-2.jpg', name: 'Necroses myocardii. Calcificatio. Hypovitaminosis', sample: 'D-63a-2', class: '', description:''},
          ]
        },
        {
          id:'exc05',
          title: 'Упражнение 5',
          subtitle: 'НЕКРОЗА- ВИДОВЕ. ГАНГРЕНА',
          images: [
            {filename:'exc-05/Gangraena pulmonum G-167 2.JPG',name:'Gangraena pulmonum G-167 2', description: ''},
            {filename:'exc-05/Gangraena pulmonum G-167 1.JPG',name:'Gangraena pulmonum G-167 1', description: ''},
            {filename:'exc-05/Degeneratio toxica hepatis B-262.JPG',name:'Degeneratio toxica hepatis B-262', description: ''},
            {filename:'exc-05/Degeneratio toxica hepatis B-262-2.JPG',name:'Degeneratio toxica hepatis B-262-2', description: ''},
            {filename:'exc-05/Encephalomyelitis infectiosa, tygropiknosis. E-216-1.JPG',name:'Encephalomyelitis infectiosa, tygropiknosis. E-216-1', description: ''},
            {filename:'exc-05/Encephalomyelitis infectiosa. Tygropiknosis E-216-2.JPG',name:'Encephalomyelitis infectiosa. Tygropiknosis E-216-2', description: ''},
            {filename:'exc-05/Encephalomyelitis infectiossa, tygropiknosis E-216-3.JPG',name:'Encephalomyelitis infectiossa, tygropiknosis E-216-3', description: ''},
            {filename:'exc-05/Necroses cerebeli.Encephalomalacia, Avitaminosis E D-218-1.JPG',name:'Necroses cerebeli.Encephalomalacia, Avitaminosis E D-218-1', description: ''},
            {filename:'exc-05/Necroses cerebeli. Encephalomalacia. Avitaminosis E D-218-2.JPG',name:'Necroses cerebeli. Encephalomalacia. Avitaminosis E D-218-2', description: ''},
            {filename:'exc-05/Necroses cerebeli. Encephalomalacia. Avitaminosis E D-218-4.JPG',name:'Necroses cerebeli. Encephalomalacia. Avitaminosis E D-218-4', description: ''},
            {filename:'exc-05/Necroses cerebeli. Encephalomalacia. Avitaminosis E D-218-3.JPG',name:'Necroses cerebeli. Encephalomalacia. Avitaminosis E D-218-3', description: ''},
            {filename:'exc-05/Necroses hepatis C-246 1.JPG',name:'Necroses hepatis C-246 1', description: ''},
            {filename:'exc-05/Necrobiosis renis A188 2.JPG',name:'Necrobiosis renis A188 2', description: ''},
            {filename:'exc-05/Necroses hepatis C-246 3.JPG',name:'Necroses hepatis C-246 3', description: ''},
            {filename:'exc-05/Necrobiosis renis .JPG',name:'Necrobiosis renis ', description: ''},
            {filename:'exc-05/Lymphadenitis tuberculosa. Caseosatio. F-181.JPG',name:'Lymphadenitis tuberculosa. Caseosatio. F-181', description: ''},
          ]
        },
        {
          id:'exc06',
          title: 'Упражнение 6',
          subtitle: 'ЦИРКУЛАТОРНИ НАРУШЕНИЯ- ИСХЕМИЯ ТРОМБОЗА',
          images: [
            { filename:'exc-06/CoagulumC-48-1.JPG', name: 'Coagulum бял кръвен съсирек', sample: 'C-48-2', class: '', description:''},
            { filename:'exc-06/Coagulum_бял_кръвен_съсирек C-48-2.JPG', name: 'Coagulum бял кръвен съсирек', sample: 'C-48-2', class: '', description:''},
            { filename:'exc-06/Coagulum, sanguinis_червен_кръвен_съсирекD1 83A.JPG', name: 'Coagulum, sanguinis - червен кръвен съсирек', sample: 'D1 83A', class: '', description:''},
            { filename:'exc-06/Coagulum_sanguinis_D2 83A.JPG', name: 'Coagulum sanguinis - червен кръвен съсирек', sample: 'D2 83A', class: '', description:''},
            { filename:'exc-06/Endarteritis thromboticans parasitariaE2-214.JPG', name: 'Endarteritis thromboticans parasitaria', sample: 'E2-214', class: '', description:''},
            { filename:'exc-06/Endarteritis thromboticans parasitaria_kon_arteria_s_trombotichna_masaG1 89 1.JPG', name: 'Endarteritis thromboticans parasitaria kon arteria s trombotichnа masa', sample: 'G1 89 1', class: '', description:''},
            { filename:'exc-06/Endarteritis thromboticans parasitaria_fibroblasti_fibrociti_golqmo_uvelichenie_G1 89 2.JPG', name: 'Endarteritis thromboticans parasitaria fibroblasti fibrociti golqmo uvelichenie', sample: 'G1 89 2', class: '', description:''},
            { filename:'exc-06/Endartheritis_thromboticans_parasitaria_golqmo_uvelichenie_G1 89 3.JPG', name: 'Endartheritis thromboticans parasitaria golqmo uvelichenie', sample: 'G1 89 3', class: '', description:''},
            { filename:'exc-06/Endarteriitis thromboticans parasitaria_smesen_pristenen_trombE1-214.JPG', name: 'Endarteriitis thromboticans parasitaria smesen pristenen tromb', sample: 'E1-214', class: '', description:''},
            { filename:'exc-06/Infarctus haemorrhagicus_PULMO_SWINE B-254.JPG', name: 'Infarctus haemorrhagicus_PULMO_SWINE', sample: 'B-254', class: '', description:''},
            { filename:'exc-06/Infarctus anaemicus A1 253 renis .JPG', name: 'Infarctus anaemicus renis ', sample: 'A1 253', class: '', description:''},
            { filename:'exc-06/Infarctus anaemicus A2 253 ren .JPG', name: 'Infarctus anaemicus renис ', sample: 'A2 253', class: '', description:''},
          ]
        },
        {
          id:'exc07',
          title: 'Упражнение 7',
          subtitle: 'ЦИРКУЛАТОРНИ СМУЩЕНИЯ-ХИПЕРЕМИЯ И ОТОК',
          images: [
            { filename:'exc-07/Atrophia renis F-17.JPG', name: 'Atrophia renis F-17', sample: '', class: '', description:''},
            { filename:'exc-07/Emphysema pulmonum E-8.JPG', name: 'Emphysema pulmonum E-8', sample: '', class: '', description:''},
            { filename:'exc-07/Hyperplasia et psosoplasia glandulae mucosae oesophagi D-258-2.JPG', name: 'Hyperplasia et psosoplasia glandulae mucosae oesophagi D-258-2', sample: '', class: '', description:''},
            { filename:'exc-07/Hyperplasia et prosoplasia glandulae mucosae oesophagi D-258-1.JPG', name: 'Hyperplasia et prosoplasia glandulae mucosae oesophagi D-258-1', sample: '', class: '', description:''},
            { filename:'exc-07/HYperplasia et prosoplasia glandulae mucosae oesophagi D-258-3.JPG', name: 'HYperplasia et prosoplasia glandulae mucosae oesophagi D-258-3', sample: '', class: '', description:''},
            { filename:'exc-07/HYPERAEMIA PASSIVA CUM ATROPHIA CYANOTICA HEPATIS A-263-2.JPG', name: 'HYPERAEMIA PASSIVA CUM ATROPHIA CYANOTICA HEPATIS A-263-2', sample: '', class: '', description:''},
            { filename:'exc-07/HYPERAEMIA PASSIVA CUM CYANOTICA HEPATIS A-263-1.JPG', name: 'HYPERAEMIA PASSIVA CUM CYANOTICA HEPATIS A-263-1', sample: '', class: '', description:''},
            { filename:'exc-07/HYPERAEMIA PASSIVA ET OEDEMA STAGNATIONIS HPEATIS B-237-1.JPG', name: 'Hyperaemia passiva et oedema stagnationis hepatis B-237-1', sample: '', class: '', description:''},
            { filename:'exc-07/Hyperaemia passiva et oedema stagnationis hepatis B-237-2.JPG', name: 'Hyperaemia passiva et oedema stagnationis hepatis B-237-2', sample: '', class: '', description:''},
            { filename:'exc-07/Hyperaemia passiva et oedema stagnationis hepatis B-237-3.JPG', name: 'Hyperaemia passiva et oedema stagnationis hepatis B-237-3', sample: '', class: '', description:''},
            { filename:'exc-07/oEDEMA PULMONUM + ANTHRACOSIS C-12a-1.JPG', name: 'Oedema pulmonum anthracosis C-12a-1', sample: '', class: '', description:''},
            { filename:'exc-07/Oedema pulmonum anthracosis C-12a-2.JPG', name: 'Oedema pulmonum anthracosis C-12a-2', sample: '', class: '', description:''},
          ]
        },
        {
          id:'exc08',
          title: 'Упражнение 8',
          subtitle: 'ВЪЗПАЛЕНИЕ- ОБЩО. КЛАСИФИКАЦИЯ',
          images: [
            { filename:'exc-08/ABSCESSUS HEPATIS D-143-1.JPG', name: 'ABSCESSUS HEPATIS D-143-1', sample: '', class: '', description:''},
            { filename:'exc-08/ABSCESSUS HEPATIS D-143-2.JPG', name: 'ABSCESSUS HEPATIS D-143-2', sample: '', class: '', description:''},
            { filename:'exc-08/ABSCESSUS HEPATISD-143-3.JPG', name: 'ABSCESSUS HEPATIS D-143-3', sample: '', class: '', description:''},
            { filename:'exc-08/ABSCESSUS HEPATIS CAPSULATIO E 50.JPG', name: 'ABSCESSUS HEPATIS CAPSULATIO E 50', sample: '', class: '', description:''},
            { filename:'exc-08/ABSCESSUS HEPATIS CAPSULATIO E 50-1.JPG', name: 'ABSCESSUS HEPATIS CAPSULATIO E 50-1', sample: '', class: '', description:''},
            { filename:'exc-08/ABSCESSUS HEPATIS CAPSULATIO E 50-2.JPG', name: 'ABSCESSUS HEPATIS CAPSULATIO E 50-2', sample: '', class: '', description:''},
            { filename:'exc-08/ABSCESSUS HEPATIS CAPSULATIO E 50-3.JPG', name: 'ABSCESSUS HEPATIS CAPSULATIO E 50-3', sample: '', class: '', description:''},
            { filename:'exc-08/BRONCHOPNEUMONIA CATARRHALIS PURULENTA H-229-1.JPG', name: 'BRONCHOPNEUMONIA CATARRHALIS PURULENTA H-229-1', sample: '', class: '', description:''},
            { filename:'exc-08/BRONCHOPNEUMONIA CATARRHALIS PURULENTA H-229-2.JPG', name: 'BRONCHOPNEUMONIA CATARRHALIS PURULENTA H-229-2', sample: '', class: '', description:''},
            { filename:'exc-08/BRONCHOPNEUMONIA CATARRHALIS PURULENTA H-229-3.JPG', name: 'BRONCHOPNEUMONIA CATARRHALIS PURULENTA H-229-3', sample: '', class: '', description:''},
            { filename:'exc-08/BRONCHOPNEUMONIA CATARHALIS C-129.JPG', name: 'BRONCHOPNEUMONIA CATARHALIS C-129', sample: '', class: '', description:''},
            { filename:'exc-08/BRONCHOPNEUMONIA CATARHALLISC-129-2.JPG', name: 'BRONCHOPNEUMONIA CATARHALISC-129-2', sample: '', class: '', description:''},
            { filename:'exc-08/BRONCHOPNEUMONIE CATARRHALIS C-129-3.JPG', name: 'BRONCHOPNEUMONIE CATARRHALIS C-129-3', sample: '', class: '', description:''},
            { filename:'exc-08/ENTERITIS CATARRHALIS B-126-1.JPG', name: 'ENTERITIS CATARHALIS B-126-1', sample: '', class: '', description:''},
            { filename:'exc-08/ENTERITIS CATAHRALIS B-126-2.JPG', name: 'ENTERITIS CATAHRALIS B-126-2', sample: '', class: '', description:''},
            { filename:'exc-08/HEPATITIS APOSTEMATOSA F-165-1.JPG', name: 'HEPATITIS APOSTEMATOSA F-165-1', sample: '', class: '', description:''},
            { filename:'exc-08/HEPATITIS APOSTEMATOSA F-165-2.JPG', name: 'HEPATITIS APOSTEMATOSA F-165-2', sample: '', class: '', description:''},
            { filename:'exc-08/HEPATITIS APOSTEMATOSA F-165-3.JPG', name: 'HEPATITIS APOSTEMATOSA F-165-3', sample: '', class: '', description:''},
            { filename:'exc-08/LYMPHADENITIS PURULENTA G-225-1.JPG', name: 'LYMPHADENITIS PURULENTA G-225-1', sample: '', class: '', description:''},
            { filename:'exc-08/LYMPHADENITIS PURULENTA G-225-2.JPG', name: 'LYMPHADENITIS PURULENTA G-225-2', sample: '', class: '', description:''},
            { filename:'exc-08/LYMPHADENITIS PURULENTA G-225-3.JPG', name: 'LYMPHADENITIS PURULENTA G-225-3', sample: '', class: '', description:''},
            { filename:'exc-08/GLOMERULONEPHRITIS SEROSA A-9-2.JPG', name: 'GLOMERULONEPHRITIS SEROSA A-9-2', sample: '', class: '', description:''},
            { filename:'exc-08/gLOMERULONEPHRITIS SEROSA A-9-1.JPG', name: 'GLOMERULONEPHRITIS SEROSA A-9-1', sample: '', class: '', description:''},
          ]
        },
        {
          id:'exc09',
          title: 'Упражнение 9',
          subtitle: 'ХЕМОРАГИЧНО, ФИБРОЗНО И ПРОЛИФЕРАТИВНО ВЪЗПАЛЕНИЕ',
          images: [
            { filename:'exc-09/Colitis deiphtheroides-Parathyphusuum D248.JPG', name: 'Colitis deiphtheroides-Parathyphusuum D248', sample: '', class: '', description:''},
            { filename:'exc-09/Colitis deiphtheroides-Parathyphusuum  D248-1.JPG', name: 'Colitis deiphtheroides-Parathyphusuum  D248-1', sample: '', class: '', description:''},
            { filename:'exc-09/Colitis deiphtheroides-Parathyphusuum  D248-2.JPG', name: 'Colitis deiphtheroides-Parathyphusuum  D248-2', sample: '', class: '', description:''},
            { filename:'exc-09/Colitis deiphtheroides-Parathyphusuum  D248-22.jpg', name: 'Colitis deiphtheroides-Parathyphusuum  D248-22', sample: '', class: '', description:''},
            { filename:'exc-09/Glomerulonephritis acuta B255-1.JPG', name: 'Glomerulonephritis acuta B255-1', sample: '', class: '', description:''},
            { filename:'exc-09/Glomerulonephritis acutaB255.JPG', name: 'Glomerulonephritis acuta B255', sample: '', class: '', description:''},
            { filename:'exc-09/Pneumonia intersticialis G-211-1.JPG', name: 'Pneumonia intersticialis G-211-1', sample: '', class: '', description:''},
            { filename:'exc-09/Pneumonia interstitialis G-211-3.JPG', name: 'Pneumonia interstitialis G-211-3', sample: '', class: '', description:''},
            { filename:'exc-09/Hepatitis interstitialis H-266.JPG', name: 'Hepatitis interstitialis H-266', sample: '', class: '', description:''},
            { filename:'exc-09/Hepatitis interstitialis  H-266-1.JPG', name: 'Hepatitis interstitialis H-266-1', sample: '', class: '', description:''},
            { filename:'exc-09/Nephritis interstitialis  F138-1.JPG', name: 'Nephritis interstitialis F138-1', sample: '', class: '', description:''},
            { filename:'exc-09/Nephritis interstitialis F138.JPG', name: 'Nephritis interstitialis F138', sample: '', class: '', description:''},
            { filename:'exc-09/Pericarditis fibrinosa C4.JPG', name: 'Pericarditis fibrinosa C4', sample: '', class: '', description:''},
            { filename:'exc-09/Pericarditis fibrinosa C4-1.JPG', name: 'Pericarditis fibrinosa C4-1', sample: '', class: '', description:''},
            { filename:'exc-09/Pericarditis fibrinosa C4-2.JPG', name: 'Pericarditis fibrinosa C4-2', sample: '', class: '', description:''},
            { filename:'exc-09/Pericarditis fibrinosa C4-3.JPG', name: 'Pericarditis fibrinosa C4-3', sample: '', class: '', description:''},
            { filename:'exc-09/Pericarditis fibrinosaC4-4.JPG', name: 'Pericarditis fibrinosa C4-4', sample: '', class: '', description:''},
            { filename:'exc-09/Pneumonia interstitialis G-211-2.JPG', name: 'Pneumonia interstitialis G-211-2', sample: '', class: '', description:''},
            { filename:'exc-09/Pneumonia crouposa  E70-1.JPG', name: 'Pneumonia crouposa  E70-1', sample: '', class: '', description:''},
            { filename:'exc-09/Pneumonia crouposa  E70-2.JPG', name: 'Pneumonia crouposa  E70-2', sample: '', class: '', description:''},
            { filename:'exc-09/Pneumonia crouposa  E70-3.JPG', name: 'Pneumonia crouposa  E70-3', sample: '', class: '', description:''},
            { filename:'exc-09/Pneumonia crouposa E70.JPG', name: 'Pneumonia crouposa E70', sample: '', class: '', description:''},
            { filename:'exc-09/Enteritis haemorrhagica A121.JPG', name: 'Enteritis haemorrhagica A121', sample: '', class: '', description:''},
            { filename:'exc-09/Enteritis haemorrhagica  A121-1.JPG', name: 'Enteritis haemorrhagica A121-1', sample: '', class: '', description:''},
            { filename:'exc-09/Enteritis haemorrhagica  A121-2.JPG', name: 'Enteritis haemorrhagica A121-2', sample: '', class: '', description:''},
            { filename:'exc-09/Enteritis haemorrhagica  A121-3.JPG', name: 'Enteritis haemorrhagica A121-3', sample: '', class: '', description:''},
          ]
        },
        {
          id:'exc10',
          title: 'Упражнение 10',
          subtitle: 'ГРАНУЛОМНИ ВЪЗПАЛЕНИЯ',
          images: [
            { filename:'exc-10/PNEUMONIA MYCOTICA D184.JPG', name: 'PNEUMONIA MYCOTICA D184', sample: '', class: '', description:''},
            { filename:'exc-10/Pneumonia mycotica D184-2.JPG', name: 'Pneumonia mycotica D184-2', sample: '', class: '', description:''},
            { filename:'exc-10/Pneumonia mycotica D184-1.JPG', name: 'Pneumonia mycotica D184-1', sample: '', class: '', description:''},
            { filename:'exc-10/Pneumonia spergilosa E250.JPG', name: 'Pneumonia spergilosa E250', sample: '', class: '', description:''},
            { filename:'exc-10/Pneumonia spergilosa  E250-1.JPG', name: 'Pneumonia spergilosa  E250-1', sample: '', class: '', description:''},
            { filename:'exc-10/Pneumonia spergilosa E250-2.JPG', name: 'Pneumonia spergilosa E250-2', sample: '', class: '', description:''},
            { filename:'exc-10/LYMPHADENITIS TUBERCULOSA A16.JPG', name: 'LYMPHADENITIS TUBERCULOSA A16', sample: '', class: '', description:''},
            { filename:'exc-10/LYMPHADENITIS TUBERCULOSA  A16-1.JPG', name: 'LYMPHADENITIS TUBERCULOSA  A16-1', sample: '', class: '', description:''},
            { filename:'exc-10/LYMPHADENITIS TUBERCULOSA A16-2.JPG', name: 'LYMPHADENITIS TUBERCULOSA A16-2', sample: '', class: '', description:''},
            { filename:'exc-10/ACTINOMYCOSIS  C78.JPG', name: 'ACTINOMYCOSIS  C78', sample: '', class: '', description:''},
            { filename:'exc-10/ACTINOMYCOSIS  C78-1.JPG', name: 'ACTINOMYCOSIS  C78-1', sample: '', class: '', description:''},
            { filename:'exc-10/ACTINOMYCOSIS  C78-2.JPG', name: 'ACTINOMYCOSIS  C78-2', sample: '', class: '', description:''},
            { filename:'exc-10/ACTINOMYCOSIS  C78-3.JPG', name: 'ACTINOMYCOSIS  C78-3', sample: '', class: '', description:''},
            { filename:'exc-10/ACTINOMYCOSIS  C78-4.JPG', name: 'ACTINOMYCOSIS  C78-4', sample: '', class: '', description:''},
            { filename:'exc-10/ACTINOMYCOSIS B32.JPG', name: 'ACTINOMYCOSIS B32', sample: '', class: '', description:''},
            { filename:'exc-10/ACTINOMYCOSIS  B32-1.JPG', name: 'ACTINOMYCOSIS  B32-1', sample: '', class: '', description:''},
            { filename:'exc-10/ACTINOMYCOSIS  B32-2.JPG', name: 'ACTINOMYCOSIS  B32-2', sample: '', class: '', description:''},
            { filename:'exc-10/Enteritis paratuberculosa F256.JPG', name: 'Enteritis paratuberculosa F256', sample: '', class: '', description:''},
            { filename:'exc-10/Enteritis paratuberculosa F256-1.JPG', name: 'Enteritis paratuberculosa F256-1', sample: '', class: '', description:''},
            { filename:'exc-10/Enteritis paratuberculosa F256-2.JPG', name: 'Enteritis paratuberculosa F256-2', sample: '', class: '', description:''},
          ]
        },
        {
          id:'exc11',
          title: 'Упражнение 11',
          subtitle: 'Неоплазии-ОБЩО',
          images: [
            { filename:'exc-11/Sarcoma fuscocellulare D46-1.JPG', name: 'Sarcoma fuscocellulare D46-1', sample: '', class: '', description:''},
            { filename:'exc-11/Sarcoma fuscocellulare D46-2.JPG', name: 'Sarcoma fuscocellulare D46-2', sample: '', class: '', description:''},
            { filename:'exc-11/Sarcoma globocellulare B45.JPG', name: 'Sarcoma globocellulare B45', sample: '', class: '', description:''},
            { filename:'exc-11/Sarcoma globocellulare  B45-1.JPG', name: 'Sarcoma globocellulare  B45-1', sample: '', class: '', description:''},
            { filename:'exc-11/Sarcoma gigantocellulare e 43 1.JPG', name: 'Sarcoma gigantocellulare e 43 1', sample: '', class: '', description:''},
            { filename:'exc-11/Sarcoma gigantocellulare e 43 2.JPG', name: 'Sarcoma gigantocellulare e 43 2', sample: '', class: '', description:''},
            { filename:'exc-11/Sarcoma mixtocellulare C45a-1.JPG', name: 'Sarcoma mixtocellulare C45a-1', sample: '', class: '', description:''},
            { filename:'exc-11/Fibroma durum A151a-1.JPG', name: 'Fibroma durum A151a-1', sample: '', class: '', description:''},
            { filename:'exc-11/Fibroma durum A151a-3.JPG', name: 'Fibroma durum A151a-3', sample: '', class: '', description:''},
            { filename:'exc-11/Fibroma durum A151a-2.JPG', name: 'Fibroma durum A151a-2', sample: '', class: '', description:''},
            { filename:'exc-11/Fibroma durum A151.JPG', name: 'Fibroma durum A151', sample: '', class: '', description:''},
            { filename:'exc-11/Fibroma molle oedematosum A151b-2.JPG', name: 'Fibroma molle oedematosum A151b-2', sample: '', class: '', description:''},
            { filename:'exc-11/Myxofibroma 247a.JPG', name: 'Myxofibroma 247a', sample: '', class: '', description:''},
            { filename:'exc-11/Myxofibroma F247a-1.JPG', name: 'Myxofibroma F247a-1', sample: '', class: '', description:''},
            { filename:'exc-11/Sarcoma mixtocellulareC45a-2.JPG', name: 'Sarcoma mixtocellulareC45a-2', sample: '', class: '', description:''},
            { filename:'exc-11/Sarcoma mixtocellulare C45a-3.JPG', name: 'Sarcoma mixtocellulare C45a-3', sample: '', class: '', description:''},
          ]
        },
        {
          id:'exc12',
          title: 'Упражнение 12',
          subtitle: 'ДОБРОКАЧЕСТВЕНИ И ЗЛОКАЧЕСТВЕНИ ТУМОРИ',
          images: [
            { filename:'exc-12/RHABDOMYOSARCOMA  h 260 2.JPG', name: 'RHABDOMYOSARCOMA  h 260 2', sample: '', class: '', description:''},
            { filename:'exc-12/RHABDOMYOSARCOMA h 260 1.JPG', name: 'RHABDOMYOSARCOMA h 260 1', sample: '', class: '', description:''},
            { filename:'exc-12/NEURINOMA e 197 1.JPG', name: 'NEURINOMA e 197 1', sample: '', class: '', description:''},
            { filename:'exc-12/NEURINOMA  e 197.JPG', name: 'NEURINOMA  e 197', sample: '', class: '', description:''},
            { filename:'exc-12/NEURINOMA  e197 3.JPG', name: 'NEURINOMA  e197 3', sample: '', class: '', description:''},
            { filename:'exc-12/GLIOMA d 187.JPG', name: 'GLIOMA d 187', sample: '', class: '', description:''},
            { filename:'exc-12/GLIOMA d- 187.JPG', name: 'GLIOMA d- 187', sample: '', class: '', description:''},
            { filename:'exc-12/HAEMANGIENDOTHELIOMA b- 257.JPG', name: 'HAEMANGIENDOTHELIOMA b- 257', sample: '', class: '', description:''},
            { filename:'exc-12/HAEMANGIENDOTHELIOMA b - 257.JPG', name: 'HAEMANGIENDOTHELIOMA b - 257', sample: '', class: '', description:''},
            { filename:'exc-12/HAEMANGIENDOTHELIOMA b 257.JPG', name: 'HAEMANGIENDOTHELIOMA b 257', sample: '', class: '', description:''},
            { filename:'exc-12/HAEMANGIOMA CAVERNOSUM HEPAR a-91 1.JPG', name: 'HAEMANGIOMA CAVERNOSUM HEPAR a-91 1', sample: '', class: '', description:''},
            { filename:'exc-12/HAEMANGIOMA CAVERNOSUM a-91 2.JPG', name: 'HAEMANGIOMA CAVERNOSUM a-91 2', sample: '', class: '', description:''},
            { filename:'exc-12/LEUCOSIS HEPATIS c 268 1.JPG', name: 'LEUCOSIS HEPATIS c 268 1', sample: '', class: '', description:''},
            { filename:'exc-12/LEUCOSIS HEPATIS c 268 2.JPG', name: 'LEUCOSIS HEPATIS c 268 2', sample: '', class: '', description:''},
            { filename:'exc-12/LEUCOSIS HEPATIS c 268 3.JPG', name: 'LEUCOSIS HEPATIS c 268 3', sample: '', class: '', description:''},
            { filename:'exc-12/LEIOMYOMA UTERI g 267 1.JPG', name: 'LEIOMYOMA UTERI g 267 1', sample: '', class: '', description:''},
            { filename:'exc-12/LEIOMYOMA UTERI g 267 2.JPG', name: 'LEIOMYOMA UTERI g 267 2', sample: '', class: '', description:''},
          ]
        },
        {
          id:'exc13',
          title: 'Упражнение 13',
          subtitle: 'ДОБРОКАЧЕСТВЕНИ ЕПИТЕЛНИ ТУМОРИ',
          images: [
            { filename:'exc-13/ADENOMA PULMONUM c 224.JPG', name: 'ADENOMA PULMONUM c 224', sample: '', class: '', description:''},
            { filename:'exc-13/ADENOMA PULMONUM c224 1.JPG', name: 'ADENOMA PULMONUM c224 1', sample: '', class: '', description:''},
            { filename:'exc-13/ADENOMAPULMONUM c224 2.JPG', name: 'ADENOMA PULMONUM c224 2', sample: '', class: '', description:''},
            { filename:'exc-13/ADENOMA GLANDULAE e 270.JPG', name: 'ADENOMA GLANDULAE e 270', sample: '', class: '', description:''},
            { filename:'exc-13/ADENOMA GLANDULAE e270 1.JPG', name: 'ADENOMA GLANDULAE e270 1', sample: '', class: '', description:''},
            { filename:'exc-13/PAPILLOMA DURUM a 38a.JPG', name: 'PAPILLOMA DURUM a 38a', sample: '', class: '', description:''},
            { filename:'exc-13/PAPILLOMA DURUM  a38a 1.JPG', name: 'PAPILLOMA DURUM  a38a 1', sample: '', class: '', description:''},
            { filename:'exc-13/CONDYLLOMA b-261.JPG', name: 'CONDYLLOMA b-261', sample: '', class: '', description:''},
            { filename:'exc-13/CONDYLLOMA b 261-1.JPG', name: 'CONDYLLOMA b 261-1', sample: '', class: '', description:''},
            { filename:'exc-13/CONDYLLOMA b 261-2.JPG', name: 'CONDYLLOMA b 261-2', sample: '', class: '', description:''},
            { filename:'exc-13/CONDYLLOMA b 261-3.JPG', name: 'CONDYLLOMA b 261-3', sample: '', class: '', description:''},
            { filename:'exc-13/CYSTADENOMA PAPILIFERUM d 54 1.JPG', name: 'CYSTADENOMA PAPILIFERUM d 54 1', sample: '', class: '', description:''},
            { filename:'exc-13/CYSTADENOMA PAPILIFERUM d 54 2.JPG', name: 'CYSTADENOMA PAPILIFERUM d 54 2', sample: '', class: '', description:''},
            { filename:'exc-13/CYSTADENOMA PAPILIFERUM d 54 3.JPG', name: 'CYSTADENOMA PAPILIFERUM d 54 3', sample: '', class: '', description:''},
          ]
        },
        {
          id:'exc14',
          title: 'Упражнение 14',
          subtitle: 'ЗЛОКАЧЕСТВЕНИ ЕПИТЕЛНИ ТУМОРИ',
          images: [
            { filename:'exc-14/CARCINOMA BASOCELLULARE b-269 1.JPG', name: 'CARCINOMA BASOCELLULARE b-269 1', sample: '', class: '', description:''},
            { filename:'exc-14/CARCINOMA BASOCELLULARE b-269 2.JPG', name: 'CARCINOMA BASOCELLULARE b-269 2', sample: '', class: '', description:''},
            { filename:'exc-14/CARCINOMA BASOCELLULARE b-269 3.JPG', name: 'CARCINOMA BASOCELLULARE b-269 3', sample: '', class: '', description:''},
            { filename:'exc-14/CARCINOMA SOLIDUM c 101 1.JPG', name: 'CARCINOMA SOLIDUM c 101 1', sample: '', class: '', description:''},
            { filename:'exc-14/CARCINOMA SOLIDUM c 101 2.JPG', name: 'CARCINOMA SOLIDUM c 101 2', sample: '', class: '', description:''},
            { filename:'exc-14/CARCINOMA SOLIDUM c 101 3.JPG', name: 'CARCINOMA SOLIDUM c 101 3', sample: '', class: '', description:''},
            { filename:'exc-14/CARCINOMA PLANOCELULARE KERATOIDES (CANCROID) a 127 1.JPG', name: 'CARCINOMA PLANOCELULARE KERATOIDES (CANCROID) a 127 1', sample: '', class: '', description:''},
            { filename:'exc-14/CARCINOMA PLANOCELULARE KERATOIDES (CANCROID) a 127 2.JPG', name: 'CARCINOMA PLANOCELULARE KERATOIDES (CANCROID) a 127 2', sample: '', class: '', description:''},
            { filename:'exc-14/CARCINOMA PLANOCELULARE KERATOIDES (CANCROID) a 127 3.JPG', name: 'CARCINOMA PLANOCELULARE KERATOIDES (CANCROID) a 127 3', sample: '', class: '', description:''},
            { filename:'exc-14/ADENOCARCINOMA GLANDULAE SUDORIFERAE d 61 1.JPG', name: 'ADENOCARCINOMA GLANDULAE SUDORIFERAE d 61 1', sample: '', class: '', description:''},
            { filename:'exc-14/ADENOCARCINOMA GLANDULAE SUDORIFERAE d 61 2.JPG', name: 'ADENOCARCINOMA GLANDULAE SUDORIFERAE d 61 2', sample: '', class: '', description:''},
            { filename:'exc-14/MELANOMA MALIGNUM f 242 1.JPG', name: 'MELANOMA MALIGNUM f 242 1', sample: '', class: '', description:''},
            { filename:'exc-14/MELANOMA MALIGNUM f 242 2.JPG', name: 'MELANOMA MALIGNUM f 242 2', sample: '', class: '', description:''},
            { filename:'exc-14/MELANOMA MALIGNUM (MELANOSRACOMA)e 271 1.JPG', name: 'MELANOMA MALIGNUM (MELANOSRACOMA)', sample: 'e 271 1', class: '', description:''},
            { filename:'exc-14/MELANOMA MALIGNUM e 271 2.JPG', name: 'MELANOMA MALIGNUM (MELANOSRACOMA)', sample: 'e 271 2', class: '', description:''},
          ]
        },
      ] }
  }
})
